name: Deploy Caddy

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Caddy
    env:
      TS_MACHINE: ${{ secrets.TS_MACHINE }}
      TS_USER: ${{ secrets.TS_USER }}
    steps:
      - name: Setup Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: deployment
          sparse-checkout: |
            containers
      - name: Install Quadlet files to host
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          echo "TS_AUTHKEY=$TS_AUTHKEY" > containers/systemd/.env
          echo "CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN" >> containers/systemd/.env

          ssh -o StrictHostKeyChecking=no $TS_USER@$TS_MACHINE "systemctl --user is-active caddy.service && systemctl --user stop caddy.service || true"

          ssh -o StrictHostKeyChecking=no $TS_USER@$TS_MACHINE "mkdir -p -- ~/caddy/conf ~/caddy/data ~/caddy/config ~/tailscaled/state ~/.config/containers/systemd"
          ssh -o StrictHostKeyChecking=no $TS_USER@$TS_MACHINE "test -f ~/caddy/conf/Caddyfile || touch ~/caddy/conf/Caddyfile"
          scp -o StrictHostKeyChecking=no -r containers/systemd/. $TS_USER@$TS_MACHINE:~/.config/containers/systemd/

          ssh -o StrictHostKeyChecking=no $TS_USER@$TS_MACHINE "systemctl --user daemon-reload"
      - name: Start Caddy
        run: |
          ssh -o StrictHostKeyChecking=no $TS_USER@$TS_MACHINE "systemctl --user start caddy.service"
